name: "Check Build"

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Restore tools
        run: dotnet tool restore

      - name: Check formatting
        run: dotnet csharpier check .

      - name: Restore dependencies
        run: dotnet restore -warnaserror

      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack Speckle.InterfaceGenerator/Speckle.InterfaceGenerator.csproj --configuration Release --no-build --output artifacts
